apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: classic
  nfs:
    path: "/data/mydata/"
    server: 192.168.80.10
