apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: classic
  nfs:
    path: "/data/mydata/"
    server: 192.168.80.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  storageClassName: classic
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-httpd
spec:
  selector:
    matchLabels:
      app: my-httpd
  template:
    metadata:
      labels:
        app: my-httpd
    spec:
      containers:
      - name: my-httpd
        image: httpd
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: htdocs
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: htdocs
        persistentVolumeClaim:
          claimName: pvc1
---
apiVersion: v1
kind: Service
metadata:
  name: my-httpd
spec:
  type: NodePort
  selector:
    app: my-httpd
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31080  # Sửa NodePort thành nodePort
    protocol: TCP
