apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: classic
  nfs:
    path: "/data/mydata/"
    server: "192.168.80.10"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  storageClassName: classic
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
