apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-httpd
  template:
    metadata:
      labels:
        app: my-httpd
    spec:
      containers:
      - name: my-httpd
        image: httpd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: htdocs
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: htdocs
        persistentVolumeClaim:
          claimName: pvc1
---
apiVersion: v1
kind: Service
metadata:
  name: my-httpd
spec:
  type: ClusterIP
  selector:
    app: my-httpd
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: test.vuan3086.id.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-httpd
            port:
              number: 80
  tls:
    - hosts:
      - test.vuan3086.id.vn
      secretName: default-server-secret
