apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deployapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployapp
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 90
