apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: cert-volumes
          secret:
            secretName: "my-tls-secret"
      containers:
        - name: nginx
          image: an11113/test:nginx
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: cert-volumes
              mountPath: "/certs"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31080
      name: http
      protocol: TCP
    - port: 443
      targetPort: 443
      nodePort: 31443
      name: https
      protocol: TCP
