apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
  namespace: default  # Sử dụng namespace mặc định hoặc tạo namespace riêng cho ứng dụng của bạn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: default  # Sử dụng cùng namespace với Deployment
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: default  # Sử dụng cùng namespace với Deployment và Service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Đảm bảo sử dụng lớp Ingress "nginx"
  rules:
  - host: test.vuan3086.id.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app  # Tên của service
            port:
              number: 80
