apiVersion: v1
kind: Pod
metadata:
  name: nginx-swarmtest
  labels:
    app: myapp
spec:
  nodeSelector:
    kubernetes.io/hostname: worker1
  volumes:
    - name: myvol
      hostPath:
        path: /home/html/
  containers:
  - name: n1
    image: nginx:1.17.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: myvol
        mountPath: /usr/share/nginx/html
  - name: s1
    image: ichte/swarmtest:node
    resources:
      limits:
        memory: "150Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085
    volumeMounts:
      - name: myvol
        mountPath: /data/
